[workspace]
members = ["pyo3-stub-gen", "pyo3-stub-gen-derive"]
resolver = "2"

[workspace.dependencies]
pyo3-stub-gen = { version = "0.1.0", path = "pyo3-stub-gen" }
pyo3-stub-gen-derive = { version = "0.1.0", path = "pyo3-stub-gen-derive" }

anyhow = "1.0.79"
insta = "1.34.0"
inventory = "0.3.14"
itertools = "0.12.0"
prettyplease = "0.2.16"
proc-macro2 = "1.0.74"
pyo3 = "0.20.1"
quote = "1.0.35"
syn = "2.0.46"
