name: Python

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build and install
        run: |
          pip install -v ./pyo3-stub-gen-testing[test]

      - name: Python Test
        run: pytest

      - name: Type check
        run: pyright
